package cn.itrip.dao;

import cn.itrip.beans.pojo.AreaDic;
import cn.itrip.beans.pojo.LabelDic;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface AreaDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insert(AreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insertSelective(AreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    AreaDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKeySelective(AreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKey(AreaDic record);

    List<AreaDic> getItripAreaDicListByMap(Map<String, Object> param);



}