package cn.itrip.dao;

import cn.itrip.beans.pojo.HotelFeature;

public interface HotelFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insert(HotelFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insertSelective(HotelFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    HotelFeature selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKeySelective(HotelFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKey(HotelFeature record);
}