package cn.itrip.dao;

import cn.itrip.beans.pojo.HotelOrder;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface HotelOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insert(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insertSelective(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    HotelOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKeySelective(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKey(HotelOrder record);

    //通过条件查询【爱旅行项目的酒店订单列表】
    List<HotelOrder> getItripHotelOrderListByMap(Map<String, Object> param)throws Exception;

    Integer updateHotelOrderStatus(@Param(value = "id")Long id, @Param(value = "modifiedBy")Long modifiedBy) throws Exception;


}