package cn.itrip.dao;

import cn.itrip.beans.pojo.LabelDic;

public interface LabelDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insert(LabelDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insertSelective(LabelDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    LabelDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKeySelective(LabelDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKey(LabelDic record);
}