package cn.itrip.dao;

import cn.itrip.beans.pojo.UserLinkUser;

public interface UserLinkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insert(UserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insertSelective(UserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    UserLinkUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKeySelective(UserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKey(UserLinkUser record);
}