package cn.itrip.dao;

import cn.itrip.beans.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    int updateByPrimaryKey(User record);
}