package cn.itrip.beans.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.productId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.orderId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.productType
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer producttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.userId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.isHavingImg
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer ishavingimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.positionScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer positionscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.facilitiesScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer facilitiesscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.serviceScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer servicescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.hygieneScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer hygienescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.score
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.tripMode
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String tripmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.isOk
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer isok;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.content
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Comment(Long id, Long hotelid, Long productid, Long orderid, Integer producttype, Long userid, Integer ishavingimg, Integer positionscore, Integer facilitiesscore, Integer servicescore, Integer hygienescore, Integer score, String tripmode, Integer isok, Date creationdate, Long createdby, Date modifydate, Long modifiedby, String content) {
        this.id = id;
        this.hotelid = hotelid;
        this.productid = productid;
        this.orderid = orderid;
        this.producttype = producttype;
        this.userid = userid;
        this.ishavingimg = ishavingimg;
        this.positionscore = positionscore;
        this.facilitiesscore = facilitiesscore;
        this.servicescore = servicescore;
        this.hygienescore = hygienescore;
        this.score = score;
        this.tripmode = tripmode;
        this.isok = isok;
        this.creationdate = creationdate;
        this.createdby = createdby;
        this.modifydate = modifydate;
        this.modifiedby = modifiedby;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Comment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.id
     *
     * @return the value of itrip_comment.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.id
     *
     * @param id the value for itrip_comment.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.hotelId
     *
     * @return the value of itrip_comment.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.hotelId
     *
     * @param hotelid the value for itrip_comment.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.productId
     *
     * @return the value of itrip_comment.productId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.productId
     *
     * @param productid the value for itrip_comment.productId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.orderId
     *
     * @return the value of itrip_comment.orderId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.orderId
     *
     * @param orderid the value for itrip_comment.orderId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.productType
     *
     * @return the value of itrip_comment.productType
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.productType
     *
     * @param producttype the value for itrip_comment.productType
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setProducttype(Integer producttype) {
        this.producttype = producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.userId
     *
     * @return the value of itrip_comment.userId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.userId
     *
     * @param userid the value for itrip_comment.userId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.isHavingImg
     *
     * @return the value of itrip_comment.isHavingImg
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getIshavingimg() {
        return ishavingimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.isHavingImg
     *
     * @param ishavingimg the value for itrip_comment.isHavingImg
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setIshavingimg(Integer ishavingimg) {
        this.ishavingimg = ishavingimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.positionScore
     *
     * @return the value of itrip_comment.positionScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getPositionscore() {
        return positionscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.positionScore
     *
     * @param positionscore the value for itrip_comment.positionScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setPositionscore(Integer positionscore) {
        this.positionscore = positionscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.facilitiesScore
     *
     * @return the value of itrip_comment.facilitiesScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getFacilitiesscore() {
        return facilitiesscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.facilitiesScore
     *
     * @param facilitiesscore the value for itrip_comment.facilitiesScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setFacilitiesscore(Integer facilitiesscore) {
        this.facilitiesscore = facilitiesscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.serviceScore
     *
     * @return the value of itrip_comment.serviceScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getServicescore() {
        return servicescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.serviceScore
     *
     * @param servicescore the value for itrip_comment.serviceScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setServicescore(Integer servicescore) {
        this.servicescore = servicescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.hygieneScore
     *
     * @return the value of itrip_comment.hygieneScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getHygienescore() {
        return hygienescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.hygieneScore
     *
     * @param hygienescore the value for itrip_comment.hygieneScore
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setHygienescore(Integer hygienescore) {
        this.hygienescore = hygienescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.score
     *
     * @return the value of itrip_comment.score
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.score
     *
     * @param score the value for itrip_comment.score
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.tripMode
     *
     * @return the value of itrip_comment.tripMode
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getTripmode() {
        return tripmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.tripMode
     *
     * @param tripmode the value for itrip_comment.tripMode
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setTripmode(String tripmode) {
        this.tripmode = tripmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.isOk
     *
     * @return the value of itrip_comment.isOk
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.isOk
     *
     * @param isok the value for itrip_comment.isOk
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setIsok(Integer isok) {
        this.isok = isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.creationDate
     *
     * @return the value of itrip_comment.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.creationDate
     *
     * @param creationdate the value for itrip_comment.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.createdBy
     *
     * @return the value of itrip_comment.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.createdBy
     *
     * @param createdby the value for itrip_comment.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.modifyDate
     *
     * @return the value of itrip_comment.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.modifyDate
     *
     * @param modifydate the value for itrip_comment.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.modifiedBy
     *
     * @return the value of itrip_comment.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.modifiedBy
     *
     * @param modifiedby the value for itrip_comment.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.content
     *
     * @return the value of itrip_comment.content
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.content
     *
     * @param content the value for itrip_comment.content
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}