package cn.itrip.beans.pojo;

import java.util.Date;

public class HotelTradingArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_trading_area.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_trading_area.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_trading_area.areaId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_trading_area.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_trading_area.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_trading_area.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_trading_area.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_trading_area
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public HotelTradingArea(Long id, Long hotelid, Long areaid, Date creationdate, Long createdby, Date modifydate, Long modifiedby) {
        this.id = id;
        this.hotelid = hotelid;
        this.areaid = areaid;
        this.creationdate = creationdate;
        this.createdby = createdby;
        this.modifydate = modifydate;
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_trading_area
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public HotelTradingArea() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_trading_area.id
     *
     * @return the value of itrip_hotel_trading_area.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_trading_area.id
     *
     * @param id the value for itrip_hotel_trading_area.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_trading_area.hotelId
     *
     * @return the value of itrip_hotel_trading_area.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_trading_area.hotelId
     *
     * @param hotelid the value for itrip_hotel_trading_area.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_trading_area.areaId
     *
     * @return the value of itrip_hotel_trading_area.areaId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_trading_area.areaId
     *
     * @param areaid the value for itrip_hotel_trading_area.areaId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setAreaid(Long areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_trading_area.creationDate
     *
     * @return the value of itrip_hotel_trading_area.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_trading_area.creationDate
     *
     * @param creationdate the value for itrip_hotel_trading_area.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_trading_area.createdBy
     *
     * @return the value of itrip_hotel_trading_area.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_trading_area.createdBy
     *
     * @param createdby the value for itrip_hotel_trading_area.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_trading_area.modifyDate
     *
     * @return the value of itrip_hotel_trading_area.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_trading_area.modifyDate
     *
     * @param modifydate the value for itrip_hotel_trading_area.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_trading_area.modifiedBy
     *
     * @return the value of itrip_hotel_trading_area.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_trading_area.modifiedBy
     *
     * @param modifiedby the value for itrip_hotel_trading_area.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}