package cn.itrip.beans.pojo;

import java.util.Date;

public class HotelWithBLOBs extends Hotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.details
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.facilities
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String facilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelPolicy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String hotelpolicy;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public HotelWithBLOBs(Long id, String hotelname, Long countryid, Long provinceid, Long cityid, String address, Integer hoteltype, Integer hotellevel, Integer isgrouppurchase, String redundantcityname, String redundantprovincename, String redundantcountryname, Integer redundanthotelstore, Date creationdate, Long createdby, Date modifydate, Long modifiedby, String details, String facilities, String hotelpolicy) {
        super(id, hotelname, countryid, provinceid, cityid, address, hoteltype, hotellevel, isgrouppurchase, redundantcityname, redundantprovincename, redundantcountryname, redundanthotelstore, creationdate, createdby, modifydate, modifiedby);
        this.details = details;
        this.facilities = facilities;
        this.hotelpolicy = hotelpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public HotelWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.details
     *
     * @return the value of itrip_hotel.details
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.details
     *
     * @param details the value for itrip_hotel.details
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.facilities
     *
     * @return the value of itrip_hotel.facilities
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getFacilities() {
        return facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.facilities
     *
     * @param facilities the value for itrip_hotel.facilities
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setFacilities(String facilities) {
        this.facilities = facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelPolicy
     *
     * @return the value of itrip_hotel.hotelPolicy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getHotelpolicy() {
        return hotelpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelPolicy
     *
     * @param hotelpolicy the value for itrip_hotel.hotelPolicy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setHotelpolicy(String hotelpolicy) {
        this.hotelpolicy = hotelpolicy;
    }
}