package cn.itrip.beans.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class HotelRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomTitle
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String roomtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomPrice
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private BigDecimal roomprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long roombedtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer ishavingbreakfast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.payType
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.satisfaction
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long satisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isBook
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer isbook;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isCancel
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer iscancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer istimelyresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_room
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public HotelRoom(Long id, Long hotelid, String roomtitle, BigDecimal roomprice, Long roombedtypeid, Integer ishavingbreakfast, Integer paytype, Long satisfaction, Integer isbook, Integer iscancel, Integer istimelyresponse, Date creationdate, Long createdby, Date modifydate, Long modifiedby) {
        this.id = id;
        this.hotelid = hotelid;
        this.roomtitle = roomtitle;
        this.roomprice = roomprice;
        this.roombedtypeid = roombedtypeid;
        this.ishavingbreakfast = ishavingbreakfast;
        this.paytype = paytype;
        this.satisfaction = satisfaction;
        this.isbook = isbook;
        this.iscancel = iscancel;
        this.istimelyresponse = istimelyresponse;
        this.creationdate = creationdate;
        this.createdby = createdby;
        this.modifydate = modifydate;
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_room
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public HotelRoom() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.id
     *
     * @return the value of itrip_hotel_room.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.id
     *
     * @param id the value for itrip_hotel_room.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.hotelId
     *
     * @return the value of itrip_hotel_room.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.hotelId
     *
     * @param hotelid the value for itrip_hotel_room.hotelId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomTitle
     *
     * @return the value of itrip_hotel_room.roomTitle
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getRoomtitle() {
        return roomtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomTitle
     *
     * @param roomtitle the value for itrip_hotel_room.roomTitle
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setRoomtitle(String roomtitle) {
        this.roomtitle = roomtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomPrice
     *
     * @return the value of itrip_hotel_room.roomPrice
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public BigDecimal getRoomprice() {
        return roomprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomPrice
     *
     * @param roomprice the value for itrip_hotel_room.roomPrice
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setRoomprice(BigDecimal roomprice) {
        this.roomprice = roomprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomBedTypeId
     *
     * @return the value of itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getRoombedtypeid() {
        return roombedtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomBedTypeId
     *
     * @param roombedtypeid the value for itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setRoombedtypeid(Long roombedtypeid) {
        this.roombedtypeid = roombedtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isHavingBreakfast
     *
     * @return the value of itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getIshavingbreakfast() {
        return ishavingbreakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isHavingBreakfast
     *
     * @param ishavingbreakfast the value for itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setIshavingbreakfast(Integer ishavingbreakfast) {
        this.ishavingbreakfast = ishavingbreakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.payType
     *
     * @return the value of itrip_hotel_room.payType
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.payType
     *
     * @param paytype the value for itrip_hotel_room.payType
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.satisfaction
     *
     * @return the value of itrip_hotel_room.satisfaction
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getSatisfaction() {
        return satisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.satisfaction
     *
     * @param satisfaction the value for itrip_hotel_room.satisfaction
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setSatisfaction(Long satisfaction) {
        this.satisfaction = satisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isBook
     *
     * @return the value of itrip_hotel_room.isBook
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getIsbook() {
        return isbook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isBook
     *
     * @param isbook the value for itrip_hotel_room.isBook
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setIsbook(Integer isbook) {
        this.isbook = isbook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isCancel
     *
     * @return the value of itrip_hotel_room.isCancel
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getIscancel() {
        return iscancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isCancel
     *
     * @param iscancel the value for itrip_hotel_room.isCancel
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setIscancel(Integer iscancel) {
        this.iscancel = iscancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isTimelyResponse
     *
     * @return the value of itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getIstimelyresponse() {
        return istimelyresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isTimelyResponse
     *
     * @param istimelyresponse the value for itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setIstimelyresponse(Integer istimelyresponse) {
        this.istimelyresponse = istimelyresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.creationDate
     *
     * @return the value of itrip_hotel_room.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.creationDate
     *
     * @param creationdate the value for itrip_hotel_room.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.createdBy
     *
     * @return the value of itrip_hotel_room.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.createdBy
     *
     * @param createdby the value for itrip_hotel_room.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.modifyDate
     *
     * @return the value of itrip_hotel_room.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.modifyDate
     *
     * @param modifydate the value for itrip_hotel_room.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.modifiedBy
     *
     * @return the value of itrip_hotel_room.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.modifiedBy
     *
     * @param modifiedby the value for itrip_hotel_room.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}