package cn.itrip.beans.pojo;

import java.util.Date;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.type
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.targetId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long targetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.position
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.imgUrl
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_image.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Image(Long id, String type, Long targetid, Integer position, String imgurl, Date creationdate, Long createdby, Date modifydate, Long modifiedby) {
        this.id = id;
        this.type = type;
        this.targetid = targetid;
        this.position = position;
        this.imgurl = imgurl;
        this.creationdate = creationdate;
        this.createdby = createdby;
        this.modifydate = modifydate;
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Image() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.id
     *
     * @return the value of itrip_image.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.id
     *
     * @param id the value for itrip_image.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.type
     *
     * @return the value of itrip_image.type
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.type
     *
     * @param type the value for itrip_image.type
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.targetId
     *
     * @return the value of itrip_image.targetId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getTargetid() {
        return targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.targetId
     *
     * @param targetid the value for itrip_image.targetId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setTargetid(Long targetid) {
        this.targetid = targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.position
     *
     * @return the value of itrip_image.position
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.position
     *
     * @param position the value for itrip_image.position
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.imgUrl
     *
     * @return the value of itrip_image.imgUrl
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.imgUrl
     *
     * @param imgurl the value for itrip_image.imgUrl
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.creationDate
     *
     * @return the value of itrip_image.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.creationDate
     *
     * @param creationdate the value for itrip_image.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.createdBy
     *
     * @return the value of itrip_image.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.createdBy
     *
     * @param createdby the value for itrip_image.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.modifyDate
     *
     * @return the value of itrip_image.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.modifyDate
     *
     * @param modifydate the value for itrip_image.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_image.modifiedBy
     *
     * @return the value of itrip_image.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_image.modifiedBy
     *
     * @param modifiedby the value for itrip_image.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}