package cn.itrip.beans.pojo;

import java.util.Date;

public class LabelDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.name
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.value
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.description
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.parentId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.pic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public LabelDic(Long id, String name, String value, String description, Long parentid, String pic, Date creationdate, Long createdby, Date modifydate, Long modifiedby) {
        this.id = id;
        this.name = name;
        this.value = value;
        this.description = description;
        this.parentid = parentid;
        this.pic = pic;
        this.creationdate = creationdate;
        this.createdby = createdby;
        this.modifydate = modifydate;
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public LabelDic() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.id
     *
     * @return the value of itrip_label_dic.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.id
     *
     * @param id the value for itrip_label_dic.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.name
     *
     * @return the value of itrip_label_dic.name
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.name
     *
     * @param name the value for itrip_label_dic.name
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.value
     *
     * @return the value of itrip_label_dic.value
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.value
     *
     * @param value the value for itrip_label_dic.value
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.description
     *
     * @return the value of itrip_label_dic.description
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.description
     *
     * @param description the value for itrip_label_dic.description
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.parentId
     *
     * @return the value of itrip_label_dic.parentId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.parentId
     *
     * @param parentid the value for itrip_label_dic.parentId
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.pic
     *
     * @return the value of itrip_label_dic.pic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.pic
     *
     * @param pic the value for itrip_label_dic.pic
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.creationDate
     *
     * @return the value of itrip_label_dic.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.creationDate
     *
     * @param creationdate the value for itrip_label_dic.creationDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.createdBy
     *
     * @return the value of itrip_label_dic.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.createdBy
     *
     * @param createdby the value for itrip_label_dic.createdBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.modifyDate
     *
     * @return the value of itrip_label_dic.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.modifyDate
     *
     * @param modifydate the value for itrip_label_dic.modifyDate
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.modifiedBy
     *
     * @return the value of itrip_label_dic.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.modifiedBy
     *
     * @param modifiedby the value for itrip_label_dic.modifiedBy
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}