package cn.itrip.beans.pojo;

public class TradeEnds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_trade_ends.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_trade_ends.orderNo
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_trade_ends.flag
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    private Boolean flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_trade_ends
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public TradeEnds(Long id, String orderno, Boolean flag) {
        this.id = id;
        this.orderno = orderno;
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_trade_ends
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public TradeEnds() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_trade_ends.id
     *
     * @return the value of itrip_trade_ends.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_trade_ends.id
     *
     * @param id the value for itrip_trade_ends.id
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_trade_ends.orderNo
     *
     * @return the value of itrip_trade_ends.orderNo
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_trade_ends.orderNo
     *
     * @param orderno the value for itrip_trade_ends.orderNo
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_trade_ends.flag
     *
     * @return the value of itrip_trade_ends.flag
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_trade_ends.flag
     *
     * @param flag the value for itrip_trade_ends.flag
     *
     * @mbggenerated Mon Mar 25 09:29:58 CST 2019
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}